package io.github.jysohnn.kopipe.context

enum class Role(
    val description: String
) {
    USER("A message provided directly by the user"),
    ASSISTANT("A response generated by the assistant"),
    TOOL("The output produced from executing a tool or function call"),
    KNOWLEDGE("Information retrieved from external knowledge sources based on the user’s input");

    fun getSpecification(): String {
        return "[$name]: $description"
    }
}